### ISSUE TITLE
Enable to execute rust on jupyter

### ISSUE THREAD

**Issue by siruku6** [siruku6/rust-sample#24]
# Task

- Modify `Dockerfile` to enable this to execute sources written in Rust on jupyter application

# Reference

- https://zenn.dev/esaka/scraps/e9baa5851f6109

**Comment by siruku6** [comment]
# Changes

## Dockerfile

```Dockerfile
FROM rust:1.86.0-slim-bookworm

# jupyter-notebook のインストール
RUN apt-get -y install jupyter-notebook

# jupyter 上で rust を実行できるようにするためのモジュールインストール
RUN cargo install evcxr_jupyter && evcxr_jupyter --install
```

## docker-compose.yml

```yaml
services:
  service_name:
    # For jupyter-notebook
    environment:
      - TZ=Asia/Tokyo
      - JUPYTER_PORT=${JUPYTER_PORT}
    ports:
      - ${JUPYTER_PORT}:${JUPYTER_PORT}
    command: >
      bash -c "
        jupyter notebook --no-browser --ip=0.0.0.0 --port ${JUPYTER_PORT} --allow-root --NotebookApp.token='demo'
      "
```

# How to up jupyter

```bash
docker compose up
```

Then, you can access jupyter through inputting the address `localhost:8888` in your Web-browser!

**Comment by siruku6** [comment]
# Usage

## 1. Use 3rd-party crates

You can use also crate like this:

```rust
// ------------ Cell 1 ------------
:dep rand = {version = "0.9.0"}
:dep rand_distr = {version = "0.5.1"}

// ------------ Cell 2 ------------
use rand_distr::Distribution;
use rand_distr::Normal;

// ------------ Cell 3 ------------
let mu: f64 = 2.0;
let sigma: f64 = 0.5;

// デフォルトの乱数生成器を初期化します
let mut rng = rand::rng();
// 平均mu, 標準偏差sigmaの正規分布を作成します
let dist = Normal::<f64>::new(mu, sigma).unwrap();

let count: u8 = 10;
let mut vec_rand: Vec<f64> = vec![];
for _i in 0..count {
    let sample = dist.sample(&mut rng);
    vec_rand.push(sample);
}

// semi-colon ";" is not necessary, if you want to show the content of a variable
vec_rand
```

```
# Result
[2.703090693370248, 1.3848713227890754, 1.5903233081768615, 2.337430646863493, 1.4576195953368192, 2.2295065083013994, 1.9347279844765792, 2.0701905112787746, 2.059885015808421, 2.103274439888458]
```

## 2. Use your custom crates

Assuming the structure of directories like following:

```
.
├─ src/
│   ├─ optimization
│   │    ├─ mod.rs
│   │    └─ types.rs
│   ├─ lib.rs
│   └─ main.rs
└─ Cargo.toml
```

and the contents of those files are like these:

```rust
// src/optimization/types.rs
pub type Chromosome = Vec<u16>;
```


and if your `Cargo.toml` is like this, ...

```toml
[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "=3.0.0"
csv = "1.3.1"
rand = "0.9.0"
rand_chacha = "0.9.0"
rand_distr = "0.5.1"
```

You can use your crates like following:

```rust
// Cell 1
// You have to write the name of [package] in Cargo.toml here.
:dep sandbox = { path = "../" }

// Cell 2
use sandbox::optimization::types;

// Cell 3
let chromosome: types::Chromosome = vec![1, 2, 3, 4, 5];
chromosome
```

# Reference

- [evcxr: evcxr_jupyter_tour.ipynb](https://github.com/evcxr/evcxr/blob/main/evcxr_jupyter/samples/evcxr_jupyter_tour.ipynb)
- [Evcxr common usage information: Features](https://github.com/evcxr/evcxr/blob/main/COMMON.md#features)
-
